server:
  port: 8080

spring:     
    datasource:        
        driver-class-name: com.mysql.jdbc.Driver        
        url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
        username: root        
        password: 123456
    
mybatis:
  mapperLocations: classpath:/springboot_OA/mapper/*.xml

logging:
  level:
    springboot_OA.mapper: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
